import type { Product } from "@/src/shop/types";

export const shopProducts: Product[] = [
  {
    id: "vacant-tee",
    name: "vAcAnt 黑色短T",
    priceVac: 2900,
    category: "apparel",
    fulfillmentType: "physical",
    sizeOptions: ["XS", "S", "M", "L", "XL"],
    imageSrc: "/products/vacant_tee.png",
    description: "黑色短T搭配白色滴墨 vAcAnt Logo，日常百搭的入門款。",
    stock: 100000,
  },
  {
    id: "vacant-hoodie",
    name: "vAcAnt 黑色連帽上衣",
    priceVac: 5900,
    category: "apparel",
    fulfillmentType: "physical",
    sizeOptions: ["XS", "S", "M", "L", "XL"],
    imageSrc: "/products/vacant_hoodie.png",
    description: "黑色連帽上衣，正面大面積滴墨 Logo，秋冬主力單品。",
    stock: 100000,
  },
  {
    id: "vacant-shorts",
    name: "vAcAnt 黑色短褲",
    priceVac: 3200,
    category: "apparel",
    fulfillmentType: "physical",
    sizeOptions: ["XS", "S", "M", "L", "XL"],
    imageSrc: "/products/vacant_shorts.png",
    description: "輕量黑色短褲，正面大字 Logo 設計，適合休閒與運動穿搭。",
    stock: 100000,
  },
  {
    id: "vacant-beanie",
    name: "vAcAnt 黑色毛帽",
    priceVac: 2200,
    category: "apparel",
    fulfillmentType: "physical",
    imageSrc: "/products/vacant_beanie.png",
    description: "黑色針織毛帽，正面立體 Logo 布章，冬季穿搭必備。",
    stock: 100000,
  },
  {
    id: "vacant-tote-bag",
    name: "vAcAnt 黑色托特包",
    priceVac: 2600,
    category: "apparel",
    fulfillmentType: "physical",
    imageSrc: "/products/vacant_tote_bag.png",
    description: "黑色帆布托特包，搭配滴墨 Logo 刺繡，通勤與日常外出皆適用。",
    stock: 100000,
  },
  {
    id: "triplet-golden-avatar-skin",
    name: "Tung Tung Tung Sahur 黃金造型頭像",
    priceVac: 69999,
    category: "digital",
    fulfillmentType: "digital",
    isAvatar: true,
    imageSrc: "/products/triplet_golden_avatar.png",
    description:
      "金色 Tung Tung Tung Sahur 造型頭像主題，適用於個人頁與社群展示。",
    stock: 100000,
  },
  {
    id: "triplet-diamond-avatar-skin",
    name: "Tung Tung Tung Sahur 鑽石造型頭像",
    priceVac: 99999,
    category: "digital",
    fulfillmentType: "digital",
    isAvatar: true,
    imageSrc: "/products/triplet_diamond_avatar.png",
    description:
      "鑽石稜鏡質感 Tung Tung Tung Sahur 造型，主打高亮反射與收藏稀有感。",
    stock: 100000,
  },
  {
    id: "triplet-devil-avatar-skin",
    name: "Tung Tung Tung Sahur 惡魔造型頭像",
    priceVac: 699999,
    category: "digital",
    fulfillmentType: "digital",
    isAvatar: true,
    imageSrc: "/products/triplet_devil_avatar.png",
    description:
      "火焰地獄主題 Tung Tung Tung Sahur 角色造型，紅黑配色視覺衝擊強烈。",
    stock: 100000,
  },
  {
    id: "triplet-god-avatar-skin",
    name: "Tung Tung Tung Sahur 神聖造型頭像",
    priceVac: 999999,
    category: "digital",
    fulfillmentType: "digital",
    isAvatar: true,
    imageSrc: "/products/triplet_god_avatar.png",
    description: "聖光與羽翼風格 Tung Tung Tung Sahur 造型，適合高階帳號展示。",
    stock: 100000,
  },
  {
    id: "triplet-golden-statue",
    name: "Tung Tung Tung 9999純金雕像",
    priceVac: 6777777,
    category: "collectible",
    fulfillmentType: "physical",
    imageSrc: "/products/triplet_golden_statue.png",
    description:
      "實體風格金色 Tung Tung Tung Sahur 收藏雕像，附底座與限量序號感設定。",
    stock: 100000,
  },
];

export function getProductById(productId: string) {
  return shopProducts.find((product) => product.id === productId);
}
